# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_userprofile_facebook_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.TextField(default=''),
        ),
    ]
