# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20161107_1248'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoogleProfile',
        ),
        migrations.AddField(
            model_name='spotifyprofile',
            name='access_token',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='spotifyprofile',
            name='display_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='spotifyprofile',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='spotifyprofile',
            name='followers',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='spotifyprofile',
            name='profile_picture_url',
            field=models.TextField(default=''),
        ),
    ]
