# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20161111_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookprofile',
            name='devices',
            field=models.TextField(default=''),
        ),
    ]
